### PR TITLE
feat: added greater demon drops table and anim and also added slayer …

### PR DESCRIPTION
**Pull request by RSDEANEO**
## What has been done?

Added Greater Demon Drop Table 
Added Greater Demon to SlayerAssignment file

## Has your code been documented?
yes

here preview of it 
[https://streamable.com/eb6uge](url)

### CODE REVIEW

**Comment by Tyluur** [comment]
What source did you get the drop table information from?

**Comment by RSDEANEO** [comment]
> What source did you get the drop table information from?

and also looking offline wiki too for 2011 drop table

**Comment by Eikenb00m** [comment]
Use this page
https://runescape.wiki/w/Greater_demon?oldid=5091550#Drops

The greater demon has 5 drop tables, i can now only see one.
Make the follow drop tables:

1. guaranteed
2. Runes
3. Charms
4. Weapons and amour
5. Rare

Make sure you use pixels droptable generator ;)
Goodluck!

**Review by Tyluur — APPROVED** [review]
Thanks for making the changes.

**Pull request merged**
