### PR TITLE
feat: fixed players command and added locate command

### PR DESCRIPTION
**Pull request by DesecratedTree**
## What has been done?
- added "locate" command (searches region id and matches that to a list in a function)
- fixed "players" command to not have an interface pop up and to show a list of the first 10 players the game finds online. also fixed grammar when calling this command

## Media
image
image2

### CODE REVIEW

**Comment by ipkpjersi** [comment]
I think it might be nice to keep the interface in addition to showing 10 in the chat (or have an option for it or something), otherwise it's kind of like losing functionality in a way. Maybe a separate command for the interface like ::playerlist?

**Review by Tyluur — CHANGES_REQUESTED** [review]
Looks good. 

For now, we want to keep the interface showing the player listing. Besides that, good to go.

**Comment by DesecratedTree** [comment]
Updated with the following functionality:
added a "privacy" command that toggles private mode for the locate command, not letting others see your location. (this is on by default)
"players" behavior:
in combat / interface open - will send the player list through chat, limited to the first 5 players the game finds.
not in combat - will send the player list through an interface.
updated player prefixes to include crowns based on target's privilege level when using locate or players commands.

**Comment by DesecratedTree** [comment]
image
image
image
image
image

**Comment by DesecratedTree** [comment]
final push made, fixes username formatting in the locate command (was all lowercase before)

**Comment by HarleyGilpin** [comment]
I suggest we use the privacy toggle in chat window interface to handle privacy. I like to avoid using commands as much as possible.

image

**Comment by HarleyGilpin** [comment]
remove the command from pull request and the privacy feature until Tyluur finishes adding chat packets for private messages.

**Comment by DesecratedTree** [comment]
Removed privacy mode attribute and references to it in commands.

**Comment by DesecratedTree** [comment]
added wilderness as a location to prevent pvp "sniping"

**Review by HarleyGilpin — APPROVED** [review]
After reviewing the changes made in Pull Request #490, including the addition of the 'locate' command and the improvements to the 'players' command, I am pleased to accept this pull request. Great work!

**Pull request merged**
