### PR TITLE
feat: guards will stop people from stealing from stalls

### PR DESCRIPTION
**Pull request by Paleocene**
## What has been done?
Ensures guards will attack any nearby players that attempt to steal from a stall. For now only Draynor is implemented, since other stall hubs have no spawns yet

### CODE REVIEW

**Comment by ptr64** [comment]
According to the [OSRS Wiki](https://oldschool.runescape.wiki/w/Stall), a Guard should only catch you stealing if the player is within their line of sight.

**Comment by Paleocene** [comment]
You're right, I missed that!

**Comment by Paleocene** [comment]
I can't assign you as reviewer @alycii so here you go ;)

**Comment by alycii** [comment]
Nice work @Paleocene!

**Pull request merged**
