### PR TITLE
Added floor 1 stronghold of security

### PR DESCRIPTION
**Pull request by RSDEANEO**
## What has been done?

-Added floor 1 stronghold of security region 7505

floor 2 and 3 and 4 gonna be work on in the next few days

### CODE REVIEW

**Comment by alycii** [comment]
How come some NPC's have their `walkRadius` set to 0? :o

**Comment by RSDEANEO** [comment]
> How come some NPC's have their `walkRadius` set to 0? :ow

well reading and compare from this osrs spawn dump 
should make 0 default 5 then

**Comment by RSDEANEO** [comment]
> How come some NPC's have their `walkRadius` set to 0? :o

iv fixed the walkRadius btw how have said other pull to give u updated rev then

**Review by Tyluur — CHANGES_REQUESTED** [review]
As mentioned by @alycii, walk radius should always be >0.
Besides that, looks great.

**Comment by RSDEANEO** [comment]
> As mentioned by @alycii, walk radius should always be >0. Besides that, looks great.

thanks tyluur man

**Pull request closed without merging**
